package com.segnities007.stylishui.theme

import androidx.compose.ui.graphics.Color

internal object StylishPalette {
    val Ink = Color(0xFF202124)
    val Paper = Color(0xFFF0F0ED)
    val PureSurface = Color(0xFFFFFFFF)
    val SoftSurface = Color(0xFFF7F7F4)
    val Muted = Color(0xFF686A6D)
    val SoftOutline = Color(0xFFD9DAD6)
    val LightSecondary = Color(0xFF5C5F66)
    val LightSecondaryContainer = Color(0xFFE1E2EC)
    val LightTertiary = Color(0xFF5A5E6D)
    val LightTertiaryContainer = Color(0xFFDFE2F4)
    val LightError = Color(0xFFBA1A1A)
    val LightErrorContainer = Color(0xFFFFDAD6)
    val LightOnErrorContainer = Color(0xFF410002)
    val LightPrimaryContainer = Color(0xFFD6E2FF)
    val LightOnPrimaryContainer = Color(0xFF001B3E)
    val LightSurfaceVariant = Color(0xFFE4E2EC)
    val LightOutline = Color(0xFF74767D)
    val LightInverseSurface = Color(0xFF313033)
    val LightInverseOnSurface = Color(0xFFF1F0F4)
    val LightInversePrimary = Color(0xFFAAC7FF)
    val LightSurfaceContainerHigh = Color(0xFFFAFAF8)
    val LightSurfaceContainerHighest = Color(0xFFF5F5F2)
    val LightSurfaceContainerLow = Color(0xFFFCFCFA)
    val Scrim = Color(0xFF000000)

    val DarkInk = Color(0xFFE7E7E4)
    val DarkPaper = Color(0xFF151614)
    val DarkSurface = Color(0xFF1D1E1C)
    val DarkSoftSurface = Color(0xFF292A27)
    val DarkMuted = Color(0xFFB5B6B1)
    val DarkOutline = Color(0xFF454641)
    val DarkSecondary = Color(0xFFC5C6D0)
    val DarkSecondaryContainer = Color(0xFF44464E)
    val DarkTertiary = Color(0xFFC3C6D8)
    val DarkTertiaryContainer = Color(0xFF424655)
    val DarkError = Color(0xFFFFB4AB)
    val DarkErrorContainer = Color(0xFF93000A)
    val DarkOnError = Color(0xFF690005)
    val DarkOnErrorContainer = Color(0xFFFFDAD6)
    val DarkPrimaryContainer = Color(0xFF00468F)
    val DarkOnPrimaryContainer = Color(0xFFD6E2FF)
    val DarkSurfaceVariant = Color(0xFF44464E)
    val DarkOutlineColor = Color(0xFF8E9099)
    val DarkInverseSurface = Color(0xFFE6E1E6)
    val DarkInverseOnSurface = Color(0xFF313033)
    val DarkInversePrimary = Color(0xFF005FBE)
    val DarkSurfaceContainerHigh = Color(0xFF282927)
    val DarkSurfaceContainerHighest = Color(0xFF333432)
    val DarkSurfaceContainerLow = Color(0xFF1D1E1C)
    val DarkSurfaceContainerLowest = Color(0xFF0E0F0D)
}
