package com.segnities007.stylishui.theme

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.ProvidableCompositionLocal
import androidx.compose.runtime.staticCompositionLocalOf

/** Text labels used by Stylish components when no component-specific label is supplied. */
@Immutable
public data class StylishStrings(
    public val previousPage: String = "Previous page",
    public val nextPage: String = "Next page",
    public val selectedPage: String = "Selected page",
    public val selectAllRows: String = "Select all rows",
    public val selectRow: (Int) -> String = { index -> "Select row ${index + 1}" },
    public val increase: String = "Increase",
    public val decrease: String = "Decrease",
    public val close: String = "Close",
    public val cancel: String = "Cancel",
    public val confirm: String = "Confirm",
    public val edit: String = "Edit",
    public val delete: String = "Delete",
    public val loading: String = "Loading",
    public val error: String = "Error",
    public val empty: String = "No results",
    public val filter: String = "Filter",
    public val export: String = "Export",
    public val expandRow: String = "Expand row",
    public val collapseRow: String = "Collapse row",
    public val available: String = "Available",
    public val selected: String = "Selected",
    public val chooseFiles: String = "Choose files",
    public val qrCode: String = "QR code",
    public val colorRed: String = "Red",
    public val colorGreen: String = "Green",
    public val colorBlue: String = "Blue",
    public val colorAlpha: String = "Alpha",
    public val remove: String = "Remove",
    public val pageOf: (Int, Int) -> String = { page, count -> "Page $page of $count" },
    public val sortAscending: String = "Sorted ascending",
    public val sortDescending: String = "Sorted descending",
    public val moveColumnLeft: (String) -> String = { title -> "Move $title left" },
    public val moveColumnRight: (String) -> String = { title -> "Move $title right" },
    public val resizeColumn: (String) -> String = { title -> "Resize $title" },
    public val pinnedColumn: String = "Pinned column",
    public val frozenColumn: String = "Frozen column",
    public val fileSizeBytes: (Long) -> String = { bytes -> "$bytes bytes" },
    public val rowPosition: (Int) -> String = { index -> "Row ${index + 1}" },
    public val columnPosition: (String, Int) -> String = { title, index -> "$title, row ${index + 1}" },
    public val formatInteger: (Long) -> String = { it.toString() },
    public val formatDecimal: (Double) -> String = { it.toString() },
    public val formatCurrency: (Double, String) -> String = { value, currency -> "$currency${value}" },
    public val formatDate: (Int, Int, Int) -> String = { year, month, day ->
        "$year/${month.toString().padStart(2, '0')}/${day.toString().padStart(2, '0')}"
    },
    public val plural: (Int, String) -> String = { count, noun -> "$count $noun" },
)

/** Japanese defaults for applications that use Japanese UI copy. */
public val StylishJapaneseStrings: StylishStrings = StylishStrings(
    previousPage = "前のページ",
    nextPage = "次のページ",
    selectedPage = "選択中のページ",
    selectAllRows = "すべての行を選択",
    selectRow = { index -> "行${index + 1}を選択" },
    increase = "増加",
    decrease = "減少",
    close = "閉じる",
    cancel = "キャンセル",
    confirm = "確定",
    edit = "編集",
    delete = "削除",
    loading = "読み込み中",
    error = "エラー",
    empty = "該当する項目がありません",
    filter = "絞り込み",
    export = "書き出し",
    expandRow = "行を展開",
    collapseRow = "行を折りたたむ",
    available = "利用可能",
    selected = "選択済み",
    chooseFiles = "ファイルを選択",
    qrCode = "QRコード",
    colorRed = "赤",
    colorGreen = "緑",
    colorBlue = "青",
    colorAlpha = "不透明度",
    remove = "削除",
    pageOf = { page, count -> "${count}ページ中${page}ページ" },
    sortAscending = "昇順",
    sortDescending = "降順",
    moveColumnLeft = { title -> "${title}を左へ移動" },
    moveColumnRight = { title -> "${title}を右へ移動" },
    resizeColumn = { title -> "${title}の幅を変更" },
    pinnedColumn = "固定列",
    frozenColumn = "凍結列",
    fileSizeBytes = { bytes -> "${bytes}バイト" },
    rowPosition = { index -> "${index + 1}行目" },
    columnPosition = { title, index -> "${index + 1}行目、$title" },
    formatCurrency = { value, currency -> "${currency}${value}" },
    formatDate = { year, month, day -> "${year}年${month}月${day}日" },
    plural = { count, noun -> "${count}${noun}" },
)

internal val LocalStylishStrings: ProvidableCompositionLocal<StylishStrings> =
    staticCompositionLocalOf { StylishStrings() }
