#!/usr/bin/env python3
"""Validate and index the release evidence generated by Gradle.

This is intentionally independent of Gradle's producer.  It catches the class of
failure where a report exists but its checksums are empty, stale, or unrelated to
the SBOM.  A normal CI run may retain a ``REVIEW_REQUIRED`` license status; a
release workflow must pass ``--require-clean`` after legal review.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import subprocess
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_DIR = ROOT / "build/reports/release"
SHA256 = re.compile(r"^[0-9a-f]{64}$")
COORDINATE = re.compile(r"^[^:]+:[^:]+:[^:]+$")


def digest(path: Path) -> str:
    hasher = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            hasher.update(chunk)
    return hasher.hexdigest()


def source_revision() -> tuple[str, str]:
    github_sha = os.environ.get("GITHUB_SHA", "").strip()
    if github_sha:
        return github_sha, "GITHUB_SHA"
    try:
        revision = subprocess.check_output(
            ["git", "rev-parse", "HEAD"], cwd=ROOT, text=True, stderr=subprocess.DEVNULL
        ).strip()
        if revision:
            return revision, "git"
    except (OSError, subprocess.CalledProcessError):
        pass
    return "local", "unknown"


def fail(message: str) -> None:
    raise ValueError(message)


def load_json(path: Path) -> dict:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        fail(f"{path.name} is not readable JSON: {exc}")
    if not isinstance(value, dict):
        fail(f"{path.name} must contain a JSON object")
    return value


def expected_hashes(bom: dict) -> dict[str, str]:
    expected: dict[str, str] = {}
    for index, component in enumerate(bom.get("components", [])):
        if not isinstance(component, dict):
            fail(f"SBOM component[{index}] is not an object")
        properties = component.get("properties") or []
        metadata_only = any(
            isinstance(item, dict)
            and item.get("name") == "stylish:artifact"
            and item.get("value") == "metadata-only"
            for item in properties
        )
        if metadata_only:
            continue
        coordinate = ":".join(
            str(component.get(key, "")) for key in ("group", "name", "version")
        )
        hashes = component.get("hashes")
        sha = next(
            (
                item.get("content")
                for item in hashes or []
                if isinstance(item, dict) and item.get("alg") == "SHA-256"
            ),
            None,
        )
        if not COORDINATE.fullmatch(coordinate):
            fail(f"SBOM component[{index}] has invalid coordinates: {coordinate!r}")
        if not isinstance(sha, str) or not SHA256.fullmatch(sha):
            fail(f"SBOM component {coordinate} has no valid SHA-256")
        if coordinate in expected:
            fail(f"duplicate SBOM coordinate: {coordinate}")
        expected[coordinate] = sha
    return expected


def read_checksum_index(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    lines = path.read_text(encoding="utf-8").splitlines()
    if not lines:
        fail("checksums.txt is empty")
    for number, line in enumerate(lines, start=1):
        parts = line.split("  ", 1)
        if len(parts) != 2:
            fail(f"checksums.txt line {number} is not '<sha256>  <coordinate/file>'")
        sha, name = parts[0].strip(), parts[1].strip()
        if not SHA256.fullmatch(sha):
            fail(f"checksums.txt line {number} has invalid SHA-256: {sha!r}")
        if not name or name.startswith("null"):
            fail(f"checksums.txt line {number} has an invalid artifact name")
        coordinate = name.rsplit("/", 1)[0] if "/" in name else ""
        if not COORDINATE.fullmatch(coordinate):
            fail(f"checksums.txt line {number} has no coordinate prefix: {name!r}")
        if coordinate in values:
            fail(f"checksums.txt contains duplicate coordinate: {coordinate}")
        values[coordinate] = sha
    return values


def validate(root: Path, require_clean: bool) -> tuple[dict, list[Path], str]:
    required = ("sbom.json", "third-party-notices.txt", "checksums.txt", "license-check.txt")
    missing = [root / name for name in required if not (root / name).is_file()]
    if missing:
        fail("missing release evidence: " + ", ".join(path.name for path in missing))

    bom = load_json(root / "sbom.json")
    if bom.get("bomFormat") != "CycloneDX" or bom.get("specVersion") != "1.5":
        fail("sbom.json must be CycloneDX 1.5")
    components = bom.get("components")
    if not isinstance(components, list) or not components:
        fail("sbom.json has no components")
    expected = expected_hashes(bom)
    actual = read_checksum_index(root / "checksums.txt")
    if actual != expected:
        missing_coordinates = sorted(set(expected) - set(actual))
        extra_coordinates = sorted(set(actual) - set(expected))
        mismatched = sorted(
            coordinate
            for coordinate in set(expected) & set(actual)
            if expected[coordinate] != actual[coordinate]
        )
        details = []
        if missing_coordinates:
            details.append("missing=" + ",".join(missing_coordinates[:5]))
        if extra_coordinates:
            details.append("extra=" + ",".join(extra_coordinates[:5]))
        if mismatched:
            details.append("mismatched=" + ",".join(mismatched[:5]))
        fail("checksums.txt does not match SBOM hashes (" + "; ".join(details) + ")")

    license_text = (root / "license-check.txt").read_text(encoding="utf-8")
    component_match = re.search(r"^components=(\d+)$", license_text, re.MULTILINE)
    if not component_match or int(component_match.group(1)) != len(components):
        fail("license-check.txt component count does not match sbom.json")
    status_match = re.search(r"^status=(\S+)$", license_text, re.MULTILINE)
    status = status_match.group(1) if status_match else "MISSING"
    if status not in {"REVIEW_REQUIRED", "VERIFIED"}:
        fail(f"license-check.txt has unsupported status: {status}")
    if require_clean and status != "VERIFIED":
        fail("release requires license-check.txt status=VERIFIED")

    notices = (root / "third-party-notices.txt").read_text(encoding="utf-8")
    if "sourceRevision=" not in notices:
        fail("third-party-notices.txt is missing sourceRevision")
    for coordinate in expected:
        if coordinate not in notices:
            fail(f"third-party-notices.txt is missing {coordinate}")

    evidence = [root / name for name in required]
    return bom, evidence, status


def write_manifest(root: Path, evidence: list[Path], status: str) -> Path:
    revision, revision_source = source_revision()
    manifest_path = root / "evidence-manifest.json"
    manifest = {
        "schema": "stylish-ui.release-evidence-manifest.v1",
        "status": "PASS" if status == "VERIFIED" else "PASS_WITH_LICENSE_REVIEW",
        "licenseStatus": status,
        "sourceRevision": revision,
        "sourceRevisionSource": revision_source,
        "generatedAtUtc": datetime.now(timezone.utc).isoformat(),
        "artifacts": [
            {
                "path": str(path.relative_to(ROOT)),
                "sha256": digest(path),
                "sizeBytes": path.stat().st_size,
            }
            for path in evidence
        ],
    }
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return manifest_path


def validate_existing_manifest(root: Path, evidence: list[Path], status: str) -> None:
    """Reject a retained manifest that no longer describes the reports on disk."""

    path = root / "evidence-manifest.json"
    if not path.is_file():
        return
    manifest = load_json(path)
    if manifest.get("schema") != "stylish-ui.release-evidence-manifest.v1":
        fail("evidence-manifest.json has an unsupported schema")
    if manifest.get("licenseStatus") != status:
        fail("evidence-manifest.json license status is stale")
    entries = manifest.get("artifacts")
    if not isinstance(entries, list):
        fail("evidence-manifest.json artifacts must be an array")
    expected = {
        str(item.get("path")): item
        for item in entries
        if isinstance(item, dict)
    }
    if len(expected) != len(entries):
        fail("evidence-manifest.json contains duplicate or malformed artifact entries")
    current = {
        str(path.relative_to(ROOT)): {
            "sha256": digest(path),
            "sizeBytes": path.stat().st_size,
        }
        for path in evidence
    }
    if set(expected) != set(current):
        fail("evidence-manifest.json artifact set is stale")
    for name, values in current.items():
        if expected[name].get("sha256") != values["sha256"]:
            fail(f"evidence-manifest.json hash is stale for {name}")
        if expected[name].get("sizeBytes") != values["sizeBytes"]:
            fail(f"evidence-manifest.json size is stale for {name}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--directory", type=Path, default=DEFAULT_DIR)
    parser.add_argument("--require-clean", action="store_true")
    parser.add_argument("--write-manifest", action="store_true")
    args = parser.parse_args()
    root = args.directory if args.directory.is_absolute() else ROOT / args.directory
    try:
        _, evidence, status = validate(root, args.require_clean)
        if not args.write_manifest:
            validate_existing_manifest(root, evidence, status)
        manifest = write_manifest(root, evidence, status) if args.write_manifest else None
    except (OSError, ValueError) as exc:
        print(f"Release evidence: FAIL ({exc})")
        return 1
    suffix = f", manifest={manifest.relative_to(ROOT)}" if manifest else ""
    print(f"Release evidence: PASS ({len(evidence)} reports, license={status}{suffix})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
